In [2]:
import pandas as pd
import sqlite3 as sql

In [3]:
conn = sql.connect('factbook.db')
conn

In [4]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,facts,facts,47,"CREATE TABLE ""facts"" (""id"" INTEGER PRIMARY KEY..."
2,table,cities,cities,2,CREATE TABLE cities (\n id integer prim...

In [5]:
pd.read_sql_query('pragma table_info(facts)',conn)

    cid               name          type  notnull dflt_value  pk
0     0                 id       INTEGER        1       None   1
1     1               code  varchar(255)        1       None   0
2     2               name  varchar(255)        1       None   0
3     3               area       INTEGER        0       None   0
4     4          area_land       INTEGER        0       None   0
5     5         area_water       INTEGER        0       None   0
6     6         population       INTEGER        0       None   0
7     7  population_growth         float        0       None   0
8     8         birth_rate         float        0       None   0
9     9         death_rate         float        0       None   0
10   10     migration_rate         float        0       None   0

In [6]:

pd.read_sql_query('pragma table_info(cities)',conn)

   cid        name     type  notnull dflt_value  pk
0    0          id  INTEGER        0       None   1
1    1        name     TEXT        0       None   0
2    2  population  INTEGER        0       None   0
3    3     capital     bool        0       None   0
4    4    facts_id     TEXT        0       None   0

In [7]:
pd.read_sql_query('select * from facts',conn)

,id,code,name,area,area_land,area_water,population,population_growth,birth_rate,death_rate,migration_rate
0,1,af,Afghanistan,652230.0,652230.0,0.0,3.256434e+07,2.32,38.57,13.89,1.51
1,2,al,Albania,28748.0,27398.0,1350.0,3.029278e+06,0.30,12.92,6.58,3.30
2,3,ag,Algeria,2381741.0,2381741.0,0.0,3.954217e+07,1.84,23.67,4.31,0.92
3,4,an,Andorra,468.0,468.0,0.0,8.558000e+04,0.12,8.13,6.96,0.00
4,5,ao,Angola,1246700.0,1246700.0,0.0,1.962535e+07,2.78,38.78,11.49,0.46
...,...,...,...,...,...,...,...,...,...,...,...
256,257,zh,Atlantic Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,258,xo,Indian Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,259,zn,Pacific Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,260,oo,Southern Ocean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,261,xx,World,NaN,NaN,NaN,7.256490e+09,1.08,18.60,7.80,NaN

In [8]:
pd.read_sql_query('select * from cities',conn)

      id          name  population  capital facts_id
0      1    Oranjestad       37000        1      216
1      2  Saint John'S       27000        1        6
2      3     Abu Dhabi      942000        1      184
3      4         Dubai     1978000        0      184
4      5       Sharjah      983000        0      184
..   ...           ...         ...      ...      ...
392  393       Mbabane       66000        1      167
393  394         Sanaa     2419000        1      193
394  395          Aden      784000        0      193
395  396        Lusaka     1802000        1      194
396  397        Harare     1542000        1      195

[397 rows x 5 columns]

1. List all cities where the area is greater than 5000, along with their population.

In [17]:
pd.read_sql_query('''
select  c.name City_name , c.population Population ,f.area Area_name from cities c
 inner join facts f on c.facts_id =  f.id and area > 5000
''',conn)

     City_name  Population  Area_name
0    Abu Dhabi      942000      83600
1        Dubai     1978000      83600
2      Sharjah      983000      83600
3        Kabul     3097000     652230
4      Algiers     2916000    2381741
..         ...         ...        ...
349    Mbabane       66000      17364
350      Sanaa     2419000     527968
351       Aden      784000     527968
352     Lusaka     1802000     752618
353     Harare     1542000     390757

[354 rows x 3 columns]

2. List the names of capital cities where the death rate is greater than 2% and the
birth rate is less than 20%

In [21]:
pd.read_sql_query('''
select f.death_rate , f.birth_rate,c.name as Capital_City from cities c 
inner join facts f on f.id = c.facts_id where f.death_rate >2 and f.birth_rate <20

    
''',conn)

     death_rate  birth_rate      Capital_City
0          8.18       12.56        Oranjestad
1          5.69       15.85      Saint John'S
2          7.07       16.64              Baku
3          6.58       12.92            Tirana
4          9.34       13.61           Yerevan
..          ...         ...               ...
261        5.93       15.96          Haiphong
262        5.93       15.96           Da Nang
263        8.54       10.31  Charlotte Amalie
264       13.91       19.80          Windhoek
265        5.06       13.45          Mata-Utu

[266 rows x 3 columns]

3. List the cities with a population growth rate between 1% and 5%, sorted in desc
by population growth.

In [35]:
pd.read_sql_query('''
select c.name Cities_Name ,f.population_growth Population_Growth from cities c
inner join facts f on c.facts_id = f.id where f.population_growth between 1 and 5 order by 2 desc
    
''',conn)

    Cities_Name  Population_Growth
0          Juba               4.02
1      Lilongwe               3.32
2     Bujumbura               3.28
3        Niamey               3.25
4       Kampala               3.24
..          ...                ...
210         Fes               1.00
211   Marrakech               1.00
212     Tangier               1.00
213      Agadir               1.00
214     Managua               1.00

[215 rows x 2 columns]

4. Find countries that start with &quot;A&quot; and do not have any cities listed in the cities
table. The query should return the country name and city name. Using left join

In [36]:
pd.read_sql_query('''
SELECT f.name AS Country_Name,
       c.name AS City_Name
FROM facts f
LEFT JOIN cities c
ON f.id = c.facts_id
WHERE f.name LIKE 'A%'
AND c.id IS NULL
''', conn)

                  Country_Name City_Name
0  Ashmore and Cartier Islands      None
1                     Akrotiri      None
2                   Antarctica      None
3                 Arctic Ocean      None
4               Atlantic Ocean      None

5. List all capital cities and their corresponding death rate using a LEFT JOIN.

In [37]:
pd.read_sql_query('''
SELECT c.name AS Capital_City,
       f.death_rate AS Death_Rate
FROM cities c
LEFT JOIN facts f
ON c.facts_id = f.id
WHERE c.capital = 1
''', conn)

     Capital_City  Death_Rate
0      Oranjestad        8.18
1    Saint John'S        5.69
2       Abu Dhabi        1.97
3           Kabul       13.89
4         Algiers        4.31
..            ...         ...
203          Apia        5.32
204       Mbabane       13.56
205         Sanaa        6.28
206        Lusaka       12.67
207        Harare       10.13

[208 rows x 2 columns]